import { Button, VerticalBox , HorizontalBox, GridBox, ListView} from "std-widgets.slint";

struct Size {
    width: int,
    height: int
}

component Block inherits Rectangle {
    in property <color> block_color ;

    width: 24px;
    height: 24px;
    background: block-color; 
    border-width: 2px;
    border-color: block-color.darker(0.3);
}

export global GameGridAdapter { 
    in property <Size> grid_size;
    in property <[[color]]> grid;
}

component GameGrid inherits VerticalLayout {
    in property <Size> grid_size <=> GameGridAdapter.grid_size;
    in property <[[color]]> grid <=> GameGridAdapter.grid;
    
    VerticalLayout {
        spacing: 0px;
        for y in grid-size.height : HorizontalLayout {
            spacing: 0px;
            for x in grid-size.width : Block {
                block-color: grid[y][x];
            }
        }
    }
}

export component AppWindow inherits Window {

    HorizontalLayout {
        GameGrid {

        }
    } 
}
