import { Button, VerticalBox , HorizontalBox, GridBox, ListView} from "std-widgets.slint";

struct Size {
    width: int,
    height: int
}

component Block inherits Rectangle {
    in property <color> block_color ;

    width: 24px;
    height: 24px;
    background: block-color; 
    border-width: 2px;
    border-color: block-color.darker(0.3);
    border-radius: 3px;
}

export global GameAdapter { 
    in property <Size> grid_size;
    in property <[[color]]> grid;
    in property <[[color]]> next_piece;
    in property <int> score: 42;
}

component GridBlockDisplay inherits Rectangle {
    in property <Size> grid_size;
    in property <[[color]]> grid;
   
    border-width: 4px;
    border-color: self.background.darker(0.3);
    border-radius: 4px;

    VerticalLayout {
        padding: 4px;
        spacing: 0px;
        for y in grid-size.height : HorizontalLayout {
            spacing: 0px;
            for x in grid-size.width : Block {
                block-color: grid[y][x];
            }
        }
    }
}

export component AppWindow inherits Window {
    callback key-pressed(string);
    forward-focus: key-handler;

    key-handler := FocusScope {
        key-pressed(event) => {
            root.key-pressed(event.text);
            return accept;
        }
        Rectangle {
            padding: 12px;
            background: #222;
            
            HorizontalLayout {
                spacing: 24px;

                GridBlockDisplay {
                    grid_size <=> GameAdapter.grid_size;
                    grid <=> GameAdapter.grid;
                    background: #444;
                }

                VerticalLayout {
                    spacing: 10px;

                    GridBlockDisplay {
                        grid_size: { width: 4, height: 4};
                        grid <=> GameAdapter.next_piece;
                        background: #444;
                    }
                    VerticalLayout {
                        alignment: start;
                        Text {
                            text: "Score:";
                            font-size: 16px;
                            color: white;
                        }
                        Text {
                            text: GameAdapter.score;
                            color: white;
                       }
                    }
                }
            }
        }
    }
}
